import type { Metadata } from "next";
import { Geist, Geist_Mono, Inconsolata } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/header";
import Bg_code from './homepage/bg/page'

const inconsolata = Inconsolata({
  variable: "--font-inconsolata",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dimar's Portofolio",
  description: "Generated by Next",
  icons: {
    icon: '/sLogo.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inconsolata.variable} antialiased`}
      >
        <div className="justify-items-center bg-[black]">
          <Navbar />
        </div>
        <div className="bg-[black]">
          <Bg_code />
          {children}
          <div className="w-full mt-10 h-15 pt-5">
            <h1 className="text-putih text-center font-extralight text-[15px]">
              &copy; Dimar Ilham Tamara
            </h1>
          </div>
        </div>
      </body>
    </html>
  );
}
